source :gemcutter

gem "rails", "2.3.8"
gem "rake"
gem "net-ssh"
gem "net-scp"
gem "net-sftp"
gem "tzinfo" # required for Rails 2.3.x

gem 'geokit'
gem 'acts_as_tree'
gem 'acts_as_list'
gem 'inherited_resources', "1.0.6"

group :development do
  gem 'pg'
end

#group :test do
#  gem "rspec"
#  gem "rspec-rails"
#  gem "rcov"
#  gem "remarkable_rails"
#  gem 'factory_girl'
#  gem 'ZenTest'
#end

group :production do
   gem "SyslogLogger"
end
